# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master


variables:
  # Azure service connection established during pipeline creation
  azureSubscription: service-connection-rm
  appName: danielidem-api

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

# - task: AzureFunctionApp@1 # Add this at the end of your file
#   inputs:
#     azureSubscription: service-connection-rm
#     appType: functionAppLinux
#     appName: $(appName)

## Add the below snippet at the end of your pipeline
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/'
    ArtifactName: 'drop'
    # publishLocation: 'Container'

- script: |
    npm install -g @nestjs/cli
    npm install -g azure-functions-core-tools@3
    npm install
    npm run build
    npm prune --production
  displayName: 'install nestjs and deploy'

- script: |
    cd frontend-ng/
    npm install -g @angular/cli
    npm install
    export CI=1
    export CLIENT_ID='4028c136-fdda-4f91-8629-a86c47108a77'
    export CLIENT_SECRET='mevO.LONBo6vAMhZOwK2NHURlyHxkp6Ty4'
    export TENANT_ID='8cf3c4eb-960a-4ae9-8093-e276fd7a2351'
    export AZURE_SUBSCRIPTION_ID="cb89e0ef-6d83-4caf-928e-3804db1d9613"
    ng deploy
  displayName: 'install angular and deploy'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: $(azureSubscription)
    appType: 'webAppLinux'
    WebAppName: $(appName)
    Package: '$(Build.ArtifactStagingDirectory)/dist/'
    StartupCommand: 'npm run start:prod'
